version: 2.1
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"
  build:
    docker:
      - image: circleci/ruby:2.4.1
    steps:
      - checkout
      - run: echo "A first hello"  
      - run: sleep 5
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - build
      - test
